language: node_js
node_js:
 - 11

before_install:
  - curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

install:
  - yarn install
  - CI=false yarn build

cache:
  directories:
    - "node_modules"


deploy:
  provider: firebase
  token:
    secure: "1/zx7-2Gl0rXuH1mYw_hAXZhgpdRVW1xPa9VdWohYlu44"

notifications:
  email:
    recipients:
      - yjian118@uottawa.ca
    on_success: change
    on_failure: always
