language: node_js
node_js:
- 11
before_install:
- curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
- yarn global add firebase-tools
- rm -r ./src/JSONFolder
- mkdir ./src/JSONFolder
- curl -L -o ./src/JSONFolder/HtmlTopic-EN.json "https://drive.google.com/file/d/1-iDX-ziXUhtwrMD5CBya8mHRMw7i1iYB/view?usp=sharing"
- curl -L -o ./src/JSONFolder/HtmlTopic-FR.json "https://drive.google.com/file/d/1hWUO5nzYAJLIYYSsdsglRH-3mOxE01fE/view?usp=sharing"
- curl -L -o ./src/JSONFolder/HtmlTest-FR.json "https://drive.google.com/file/d/19jxhUsAnH5xEaBO3-_lORf8vM4BusJXr/view?usp=sharing"
- curl -L -o ./src/JSONFolder/HtmlTest-EN.json "https://drive.google.com/file/d/1j9dipDuGUYhraYpx2nQjTIYtXEErallE/view?usp=sharing"


install:
- yarn install
- CI=false yarn build
cache:
  directories:
  - node_modules
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: 
    - new-front-page(master)

