language: node_js
node_js:
- 11
before_install:
- curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
- yarn global add firebase-tools --prefix /usr/local
install:
- yarn install
- CI=false yarn build
cache:
  directories:
  - node_modules
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
